version: "3.8"

services:
  smarthousehub.hub:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DATABASE_FILE=SmartHouse.db
      # - DATABASE_FILE_PATH
