name: Create prod docker image 

on:
  push:
    branches: ["master"]

jobs:
  DockerImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login --username ${{ secrets.GITHUBLOGIN }} --password ${{ secrets.DockerToken }} ghcr.io

      - name: Build image
        run: docker build . --tag ghcr.io/universalsmarthouse/smarthouse-hub:latest -f ./Dockerfile

      - name: push
        run: docker push ghcr.io/universalsmarthouse/smarthouse-hub:latest
